@startuml Добавление_Вещи

actor "Пользователь" as User
participant "Интерфейс" as UI
participant "Сервис вещей" as ItemService
database "База данных" as DB

User -> UI : открыть форму добавления вещи
UI -> ItemService : добавить вещь (данные)
activate ItemService

ItemService -> DB : INSERT INTO Items
activate DB
DB --> ItemService
deactivate DB

opt Вещь хрупкая
  ItemService -> DB : отметить is_fragile = true
  activate DB
  DB --> ItemService
  deactivate DB
end

ItemService --> UI : вещь добавлена
deactivate ItemService

@enduml
