@startuml Перемещение_Вещи_В_Коробку

actor "Пользователь" as User
participant "Интерфейс" as UI
participant "Сервис вещей" as ItemService
database "База данных" as DB

User -> UI : выбрать коробку для вещи
UI -> ItemService : переместить вещь (item_id, box_id)
activate ItemService

alt Коробка существует
  ItemService -> DB : UPDATE Items SET box_id
  activate DB
  DB --> ItemService
  deactivate DB
else Коробка не найдена
  ItemService --> UI : ошибка
end

ItemService --> UI : операция завершена
deactivate ItemService

@enduml
